### ISSUE TITLE
Erlang docs not building

### ISSUE THREAD

**Issue by ccavolt** [version-fox/vfox-erlang#4]
I moved from asdf to vfox-erlang to build erlang in my project. In asdf, I was able to build the erlang docs with the KERL_BUILD_DOCS=yes environment variable, however I haven't been able to do so with vfox, with or without the environment variable. The readme in this repo says the docs should build by default, but that hasn't been my experience. Any idea what I might be doing wrong, or if there's a bug here?

<img width="438" alt="image" src="https://github.com/version-fox/vfox-erlang/assets/10134274/d7a71f0f-a919-4838-899d-11dd0ac2b844">

**Comment by yeshan333** [comment]
> I moved from asdf to vfox-erlang to build erlang in my project. In asdf, I was able to build the erlang docs with the KERL_BUILD_DOCS=yes environment variable, however I haven't been able to do so with vfox, with or without the environment variable. The readme in this repo says the docs should build by default, but that hasn't been my experience. Any idea what I might be doing wrong, or if there's a bug here?
> 
> <img alt="image" width="438" src="https://private-user-images.githubusercontent.com/10134274/330201568-d7a71f0f-a919-4838-899d-11dd0ac2b844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODM2MDQsIm5iZiI6MTcxNTY4MzMwNCwicGF0aCI6Ii8xMDEzNDI3NC8zMzAyMDE1NjgtZDdhNzFmMGYtYTkxOS00ODM4LTg5OWQtMTFkZDBhYzJiODQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZmNkNTI3MGY1ODY4NWNhNzJmMTQ2MmE2MjA2ZWUwMTMwNWJhMmQ5NDlmMTY1NzQ5M2U3YmExMDRiMGM4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jnUBJMAco1nY4sMD97fdJZhXG3TDfAUbq0dQO9ri3sw">

I released a version [v1.0.1](https://github.com/version-fox/vfox-erlang/releases/tag/v1.0.1) to fix this problem. You can update vfox-erlang plugin, then reinstall Erlang/OTP and try again.

eg: 

```shell
# 1、update plugin
vfox update erlang
# 2、remove the old version
vfox uninstall erlang@xxx
# 3、reinstall it
vfox install erlang@xxx
```

use erl to test your installation has the EEP48, for example:

![image](https://github.com/version-fox/vfox-erlang/assets/39296814/b269a006-fa96-4620-bd7c-2339c5bdbdc8)


@ccavolt

**Comment by yeshan333** [comment]
BTW. It is different from asdf-erlang internal implementation that uses [kerl](https://github.com/kerl/kerl) to manage versions. 

vfox-erlang, GNU make is directly used for installation in Unix-like systems. You can use most environment variables mentioned in official documents to control the installation process.

for an example, speed up your installation:

```shell
export MAKEFLAGS=-j8
vfox install erlang@xxx
```

reference: [https://github.com/erlang/otp/blob/master/HOWTO/INSTALL.md#building-3](https://github.com/erlang/otp/blob/master/HOWTO/INSTALL.md#building-3)

**Comment by ccavolt** [comment]
Thanks for that tip! I've been lamenting the speed of the builds and that definitely helps!

Unfortunately, regarding the docs, that hasn't fixed the issue. I'm using a devcontainer to build erlang, so I don't have to really do much to ensure I have a clean environment. You can see how I'm building it [here](https://github.com/ccavolt/devcontainer-features/blob/main/src/vfox-erlang/install.sh).

<img width="725" alt="image" src="https://github.com/version-fox/vfox-erlang/assets/10134274/b1e19f74-400b-49dc-8c05-f94aa3ccb3e7">

**Comment by yeshan333** [comment]
I looked at the [logs](https://github.com/ccavolt/devcontainer-features/actions/runs/9082895882/job/24960366143) for GitHub Actions, and it seems that the version of the plugin used is incorrect.

![image](https://github.com/version-fox/vfox-erlang/assets/39296814/f23907af-7065-43fe-9897-cb7d7cd25691)

@ccavolt

**Comment by yeshan333** [comment]
Can you offer a sample devcontainer.json for me.  I want to test it.

> Thanks for that tip! I've been lamenting the speed of the builds and that definitely helps!
> 
> Unfortunately, regarding the docs, that hasn't fixed the issue. I'm using a devcontainer to build erlang, so I don't have to really do much to ensure I have a clean environment. You can see how I'm building it [here](https://github.com/ccavolt/devcontainer-features/blob/main/src/vfox-erlang/install.sh).
> 
> <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/10134274/330524685-b1e19f74-400b-49dc-8c05-f94aa3ccb3e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDc0NDEsIm5iZiI6MTcxNTcwNzE0MSwicGF0aCI6Ii8xMDEzNDI3NC8zMzA1MjQ2ODUtYjFlMTlmNzQtNDAwYi00OWRjLThjMDUtZjk0YWEzY2NiM2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE3MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZTI4OGY5ZjRhZjY5MGQ2MjYzMzQ1ZjkzNWI0NmE1ZmZlYjc4YTRmYzVhZTdmN2EyYmQzNjBiNzgyZThjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yIqAGgxnR3ovCDyFe1VTkYCduv-TUUBo8udEG5HM3LY">

**Comment by ccavolt** [comment]
```
{
  "name": "erlang-docs-test",

  "image": "mcr.microsoft.com/devcontainers/base:ubuntu-22.04",

  "features": {
    "ghcr.io/ccavolt/devcontainer-features/vfox:0.4.0": {
      "version": "0.5.1",
      "user": "vscode",
      "shell": "zsh"
    },
    "ghcr.io/ccavolt/devcontainer-features/vfox-erlang:0.4.1": {
      "version": "26.2.5"
    },
    "ghcr.io/ccavolt/devcontainer-features/vfox-elixir:0.4.0": {
      "version": "1.16.2",
      "locale": "en_US.UTF-8",
      "defaultMixCommands": "yes"
    }
  },

  "customizations": {
    "vscode": {
      "extensions": [
        "JakeBecker.elixir-ls",
        "phoenixframework.phoenix"
      ]
    }
  }
}
```

**Comment by ccavolt** [comment]
I cut out a lot of things that aren't relevant to the example; let me know if you have any issues.

**Comment by yeshan333** [comment]
![image](https://github.com/version-fox/vfox-erlang/assets/39296814/d35d8f71-325d-4f02-ac6f-17a963512e9e)

（QAQ~😣）Can not reproduce in my machine.

❯ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by yeshan333** [comment]
I directly used an ordinary Docker container to do the experiment, and the problem did not appear.

![image](https://github.com/version-fox/vfox-erlang/assets/39296814/87a43c9d-6721-471f-918e-6995e02ee242)

Dockerfile：

```dockerfile
FROM ubuntu:22.04

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk git

RUN echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | tee /etc/apt/sources.list.d/versionfox.list \
    && apt-get update \
    && apt-get install vfox

RUN vfox add erlang && vfox install erlang@26.2.5
```

**Comment by ccavolt** [comment]
I'm in the process of creating a reproduction...in the meantime, I updated my devcontainer feature to build the docs itself, with the following lines:
```
export VFOX_CACHE=/opt/vfox
cd "${VFOX_CACHE}/erlang/v-${VERSION}/erlang-${VERSION}"
make docs DOC_TARGETS=chunks
```
Which works in my elixir project that uses that feature. I'm able to run the erl h(lists). command and don't get any complaints from ElixirLS, so I'm not sure what's going on at the moment.

**Comment by ccavolt** [comment]
I think I messed up somewhere in here. I can't build a reproduction that _doesn't_ build the docs now, so I'm just going to close this unless I find something more concrete later. Thanks so much for the fix and sorry for the wild goose chase afterwards! 😅
